- name: Deploy Watchlist
  run: |
    az sentinel watchlist create \
      --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
      --workspace-name ${{ vars.AZURE_WORKSPACE_NAME }} \
      --watchlist-alias knownLocations \
      --display-name "Known Locations" \
      --items-search-key CountryCode \
      --provider Microsoft \
      --source "Local file" \
      --raw-content @watchlists/knownLocations.csv \
      --content-type "text/csv"
